[theme]
primaryColor = "#2C3E50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1C2833"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
